export { classifyTrend } from "./trend.js";
export type { TrendOptions, TrendResult, TrendVerdict } from "./trend.js";
export { discoverRoutes, appPathsManifestSchema, routesManifestSchema } from "./manifests.js";
export type { AppPathsManifest, DiscoveredRoute, RouteKind, RoutesManifest } from "./manifests.js";
export { validateTarget, TargetError } from "./target.js";
export type { TargetErrorCode, ValidatedTarget } from "./target.js";
export { runLoadPhase, LoadError } from "./load.js";
export type { LoadPhaseOptions, LoadPhaseResult } from "./load.js";
export { runRitual } from "./ritual.js";
export type { RitualDeps, RitualOptions, RitualResult } from "./ritual.js";
export { launchInstrumented, LaunchError } from "./launcher.js";
export type { LaunchedApp, LaunchOptions } from "./launcher.js";
export { diffSnapshotFiles, diffAgainstBaseline, summarizeBaseline, retainerChain, assertReadableSnapshot, SnapshotError } from "./heap-diff.js";
export type { DiffOptions, HeapDiff, HeapLike, NodeFinding, TypeDelta } from "./heap-diff.js";
export { runMeasurement, freePort } from "./runner.js";
export type { RouteReport, RunOptions, RunnerDeps, RunReport } from "./runner.js";
export { formatReport } from "./report.js";
export { extractModuleRegistry, extractChunkModules } from "./module-registry.js";
export type { ModuleRegistry } from "./module-registry.js";
export { decodeMappings, decodeVlqLine, sourceIndexAt } from "./vlq.js";
export { attributeDiff, attributeFinding, classifySource } from "./attribution.js";
export type { AttributedDiff, FindingAttribution, Owner, RouteAttribution } from "./attribution.js";
export { loadSignatures, matchSignatures, readNextVersion } from "./signatures.js";
export type { MatchedSignature, Signature } from "./signatures.js";
export { captureEnvironment } from "./environment.js";
export type { MeasurementEnvironment } from "./environment.js";
export { renderHtmlReport } from "./html-report.js";
export { renderIssueMarkdown } from "./issue-report.js";
export type { MeasuredRoute } from "./runner.js";
export { routeSlug } from "./runner.js";
export type { RunParameters } from "./runner.js";
export { loadRouteConfig, resolveRoutePath, RouteConfigError, ROUTE_CONFIG_FILE } from "./route-config.js";
export type { RouteConfig } from "./route-config.js";
export { checkRuntime } from "./guards.js";
export { parseCliArgs, helpText } from "./cli-args.js";
