import path from "node:path";
import type { RouteReport, RunReport } from "./runner.js";

const MB = 1024 * 1024;

export type MeasuredRoute = Extract<RouteReport, { status: "measured" }>;

function evidenceRows(route: MeasuredRoute): string {
  const findings = [...(route.diff?.grownNodes ?? []), ...(route.diff?.newNodes ?? [])];
  return findings
    .slice(0, 6)
    .map((finding, index) => {
      const attribution = route.attribution?.findings[index];
      const owner =
        attribution === undefined || attribution.owner === "unattributed"
          ? "unattributed"
          : `${attribution.owner}${attribution.source ? ` — \`${attribution.source}\`` : ""}${
              attribution.packageName ? ` — ${attribution.packageName}` : ""
            }`;
      return (
        `- **${finding.kind}** \`[${finding.nodeType}] ${finding.name}\` ` +
        `${(finding.retainedBytes / MB).toFixed(2)} MB retained (${owner})\n` +
        `  - retainers: \`${finding.retainerChain || "(none)"}\``
      );
    })
    .join("\n");
}

/**
 * Issue draft in the Next.js bug-template section order. The attribution
 * gates the preamble: app/dependency-owned leaks warn against filing
 * upstream; framework/unattributed leaks read as an upstream-ready draft.
 */
export function renderIssueMarkdown(route: MeasuredRoute, run: RunReport): string {
  const environment = run.environment;
  const parameters = run.parameters;
  const owner = route.attribution?.route.owner ?? "unattributed";
  const culprit = route.attribution?.route;

  const preamble =
    owner === "app" || owner === "dependency"
      ? `> [!WARNING]\n` +
        `> next-leak attributes this leak to ${
          owner === "app"
            ? `**your own code** (\`${culprit?.source ?? "app code"}\`)`
            : `the dependency **${culprit?.packageName ?? "a dependency"}**`
        }. Fix or report it there — do **not** file this against Next.js.\n\n`
      : "";

  // Stated up front rather than left for a maintainer to discover. A draft
  // that hides what its own run could not establish is worth less than one
  // that says so: the first reviewer to spot it discounts everything else.
  const caveats =
    route.confidence.warnings.length === 0
      ? ""
      : `\n### Measurement caveats\n\n` +
        `next-leak audits its own run and reports these limits. They do not ` +
        `overturn the verdict above, but they bound how much weight it carries:\n\n` +
        route.confidence.warnings.map((warning) => `- ${warning.detail}`).join("\n") +
        `\n`;

  const curve = route.samples.map((sample) => (sample / MB).toFixed(1)).join(" → ");
  const deltas = route.trend.deltas.map((delta) => `+${(delta / MB).toFixed(2)}`).join(", ");
  const signatures = route.signatures
    .map(
      (signature) =>
        `- ${signature.historical ? "(historical) " : ""}${signature.title} — ${signature.issue}`
    )
    .join("\n");

  return `${preamble}# Memory leak on route \`${route.route}\`

Report generated by \`next-leak\` — every number below is reproducible from
the raw heap snapshots referenced at the bottom.

### Provide environment information

\`\`\`
Node.js: ${environment.nodeVersion}
OS: ${environment.platform} ${environment.arch}${environment.cpuModel ? ` (${environment.cpuModel})` : ""}
Memory: ${(environment.totalMemoryBytes / (1024 * MB)).toFixed(0)} GB
Next.js: ${environment.nextVersion ?? "unknown"}
next-leak: ${environment.nextLeakVersion}
Deployment: output "standalone", node --expose-gc --max-old-space-size=512
\`\`\`

### To Reproduce

1. Build the app with \`output: "standalone"\` and run:
   \`\`\`
   npx next-leak <app-dir>
   \`\`\`
2. next-leak boots \`.next/standalone/server.js\` in a fresh process per route and runs, against \`${route.requestPath}\`:
   warm-up ${parameters.warmupRequests} requests → forced GC → baseline heap snapshot →
   ${parameters.cycles} × [${parameters.loadRequests} requests at ${parameters.connections} connections → ${(parameters.idleMs / 1000).toFixed(0)}s idle → forced GC → post-GC sample] → final snapshot.

### Current vs. Expected behavior

**Current:** retained heap after forced GC keeps growing every cycle —
${curve} MB (per-cycle deltas ${deltas} MB), ≈ **${(route.growthPer1000Requests / MB).toFixed(2)} MB per 1000 requests**.
The first cycle is excluded from the verdict (engine warm-up).

**Expected:** retained heap flattens after warm-up (plateau), as measured on this app's healthy routes.

### Heap evidence

${evidenceRows(route) || "- (no findings above thresholds)"}
${signatures === "" ? "" : `\n**Matched known causes:**\n${signatures}\n`}${caveats}
### Verify it yourself

Raw snapshots (Chrome DevTools → Memory → Load, compare baseline vs after):

- \`${path.basename(route.baselineSnapshot)}\` / \`${path.basename(route.afterSnapshot)}\` in \`${run.workDir}\`
- machine-readable data: \`run.json\`, curves: \`report.html\`
`;
}
